Repository PKSHATechnology-Research/camphr, pull requests merged in 2020-04, with the labels that each got.

#39 add `functools.lru_cache` to knp extensions.
  camphr/pipelines/knp/__init__.py
  tests/pipelines/knp/test_knp.py
Labels: enhancement

#40 Revert sentencepiece lang from v0.4
  camphr/lang/sentencepiece/__init__.py
  docs/source/index.rst
  docs/source/notes/knp.rst
  docs/source/notes/sentencepiece.rst
  poetry.lock
  pyproject.toml
  setup.cfg
  tests/lang/sentencepiece/__init__.py
  tests/lang/sentencepiece/test_sentencepiecelang.py
Labels: enhancement

#45 Skip slow ci if unnecessary
  .github/workflows/main.yml
  README.md
  camphr/pipelines/udify.py
Labels: CI

#46 update transformers dependency
  .github/workflows/heavy_test.yml
  camphr/pipelines/transformers/tokenizer.py
  camphr/pipelines/transformers/utils.py
  poetry.lock
  pyproject.toml
Labels: enhancement

#47 dependency improvement for KNP
  camphr/pipelines/knp/dependency_parser.py
  tests/pipelines/knp/test_dependency_parser.py
Labels: enhancement

#50 fix transformers eval batchsize failure
  camphr/lang/juman/tag_map.py
  camphr/lang/torch.py
  tests/conftest.py
  tests/pipelines/knp/test_dependency_parser.py
  tests/pipelines/transformers/test_model.py
  tests/regression/test49/.gitignore
  tests/regression/test49/__init__.py
  tests/regression/test49/fail.json
  tests/regression/test49/test_main.py
  tests/utils.py
Labels: bug
